"""receipt images

Mission 10.3: receipt photos in Postgres (`RECEIPT_STORAGE=database`), because
a free host's disk is wiped on every restart and deploy. Development keeps
writing files; this table stays empty there.

Revision ID: 0fb83f8aa324
Revises: 7bd0ad0e9592
Create Date: 2026-10-06 10:30:29.956316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb83f8aa324'
down_revision: Union[str, Sequence[str], None] = '7bd0ad0e9592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_images',
    sa.Column('expense_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt_images')
    # ### end Alembic commands ###
