"""recurring bills

Also widens two CHECK constraints that autogenerate did not notice.

`Enum(..., native_enum=False)` stores a VARCHAR with a CHECK listing the allowed
values. Adding a member to the Python enum changes nothing about the column, so
**autogenerate emits no operation and `alembic check` stays clean** -- while the
database goes on rejecting the new value. Two of those had accumulated:

* `expenses.source` gained RECURRING here.
* `notifications.kind` gained BUDGET_WARNING and BUDGET_EXCEEDED with budgets,
  and BILL_DUE here. Without this, every budget alert would fail on a migrated
  database while passing in the tests.

The lists are written out rather than imported from `app.models.enums`, because
a migration has to keep saying what was true when it ran even after the enum
grows again.

Revision ID: 453f7823ac5b
Revises: 4db0da9965d6
Create Date: 2026-09-10 23:22:22.475548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453f7823ac5b'
down_revision: Union[str, Sequence[str], None] = '4db0da9965d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EXPENSE_SOURCES_BEFORE = ("MANUAL", "VOICE", "OCR", "GMAIL_API")
EXPENSE_SOURCES = (*EXPENSE_SOURCES_BEFORE, "RECURRING")

NOTIFICATION_KINDS_BEFORE = (
    "EXPENSE_ADDED",
    "COMMENT_ADDED",
    "SETTLEMENT_RECORDED",
    "PAYMENT_REMINDER",
)
NOTIFICATION_KINDS = (
    *NOTIFICATION_KINDS_BEFORE,
    "BUDGET_WARNING",
    "BUDGET_EXCEEDED",
    "BILL_DUE",
)


def _rewrite_check(table: str, column: str, name: str, values: tuple[str, ...]) -> None:
    """Replace a VARCHAR enum CHECK with one listing `values`."""
    allowed = ", ".join(f"'{value}'" for value in values)
    op.drop_constraint(name, table, type_="check")
    op.create_check_constraint(name, table, f"{column} IN ({allowed})")



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_bills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('category', sa.Enum('GROCERIES', 'RENT', 'UTILITIES', 'EATING_OUT', 'ENTERTAINMENT', 'TRANSPORT', 'OTHER', name='expensecategory_check', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('payer_id', sa.Uuid(), nullable=False),
    sa.Column('split_type', sa.Enum('EQUAL', 'EXACT', 'PERCENTAGE', 'WEIGHT', name='splittype_check', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('frequency', sa.Enum('MONTHLY', 'EVERY_2_MONTHS', 'QUARTERLY', 'YEARLY', name='recurrencefrequency_check', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('anchor_day', sa.Integer(), nullable=False),
    sa.Column('next_due_on', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('reminder_days_before', sa.Integer(), server_default='3', nullable=False),
    sa.Column('last_generated_on', sa.Date(), nullable=True),
    sa.Column('reminded_for', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('anchor_day BETWEEN 1 AND 31', name='ck_recurring_bills_anchor_day'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurring_bills_next_due_on', 'recurring_bills', ['next_due_on'], unique=False)
    op.create_table('recurring_bill_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bill_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('share_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['recurring_bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id', 'user_id', name='uq_recurring_bill_participants_bill_user')
    )
    op.add_column('expenses', sa.Column('recurring_bill_id', sa.Uuid(), nullable=True))
    op.create_index('uq_expenses_recurring_bill_due', 'expenses', ['recurring_bill_id', 'expense_date'], unique=True, postgresql_where=sa.text('recurring_bill_id IS NOT NULL'))
    op.create_foreign_key('fk_expenses_recurring_bill_id', 'expenses', 'recurring_bills', ['recurring_bill_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    _rewrite_check("expenses", "source", "expensesource_check", EXPENSE_SOURCES)
    _rewrite_check("notifications", "kind", "notificationkind_check", NOTIFICATION_KINDS)


def downgrade() -> None:
    """Downgrade schema."""
    _rewrite_check("notifications", "kind", "notificationkind_check", NOTIFICATION_KINDS_BEFORE)
    _rewrite_check("expenses", "source", "expensesource_check", EXPENSE_SOURCES_BEFORE)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_expenses_recurring_bill_id', 'expenses', type_='foreignkey')
    op.drop_index('uq_expenses_recurring_bill_due', table_name='expenses', postgresql_where=sa.text('recurring_bill_id IS NOT NULL'))
    op.drop_column('expenses', 'recurring_bill_id')
    op.drop_table('recurring_bill_participants')
    op.drop_index('ix_recurring_bills_next_due_on', table_name='recurring_bills')
    op.drop_table('recurring_bills')
    # ### end Alembic commands ###
