"""budgets

Revision ID: 4db0da9965d6
Revises: c1b68b60e3ca
Create Date: 2026-09-10 23:13:48.029878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db0da9965d6'
down_revision: Union[str, Sequence[str], None] = 'c1b68b60e3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('GROCERIES', 'RENT', 'UTILITIES', 'EATING_OUT', 'ENTERTAINMENT', 'TRANSPORT', 'OTHER', name='expensecategory_check', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('period', sa.Enum('MONTHLY', name='budgetperiod_check', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('alerted_period', sa.String(length=7), nullable=True),
    sa.Column('alerted_level', sa.Enum('OK', 'WARNING', 'EXCEEDED', name='budgetlevel_check', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'category', name='uq_budgets_group_category')
    )
    op.create_index('uq_budgets_group_overall', 'budgets', ['group_id'], unique=True, postgresql_where=sa.text('category IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_budgets_group_overall', table_name='budgets', postgresql_where=sa.text('category IS NULL'))
    op.drop_table('budgets')
    # ### end Alembic commands ###
