"""add groups.archived_at

Closing a group is not deleting it. A closed group -- a trip that ended, a flat
everyone moved out of -- stays fully readable and keeps every expense in it; it
simply takes no new spending. Nullable, so every existing group is open.

Revision ID: 5b34b813909d
Revises: 453f7823ac5b
Create Date: 2026-09-12 11:21:24.409623

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b34b813909d"
down_revision: Union[str, Sequence[str], None] = "453f7823ac5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "archived_at")
    # ### end Alembic commands ###
