"""split rules

Revision ID: 6f4106d95bd6
Revises: b0ff954ca818
Create Date: 2026-09-10 22:52:08.533272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4106d95bd6'
down_revision: Union[str, Sequence[str], None] = 'b0ff954ca818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('split_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('GROCERIES', 'RENT', 'UTILITIES', 'EATING_OUT', 'ENTERTAINMENT', 'TRANSPORT', 'OTHER', name='expensecategory_check', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'category', name='uq_split_rules_group_category')
    )
    op.create_index('uq_split_rules_group_catch_all', 'split_rules', ['group_id'], unique=True, postgresql_where=sa.text('category IS NULL'))
    op.create_table('split_rule_shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['split_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'user_id', name='uq_split_rule_shares_rule_user')
    )
    op.add_column('expenses', sa.Column('split_rule_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'split_rules', ['split_rule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'split_rule_id')
    op.drop_table('split_rule_shares')
    op.drop_index('uq_split_rules_group_catch_all', table_name='split_rules', postgresql_where=sa.text('category IS NULL'))
    op.drop_table('split_rules')
    # ### end Alembic commands ###
