"""expense comments, notifications, clock_timestamp defaults

Two new tables, plus a default swapped on three existing ones.

`now()` returns the *transaction's* start time, so every row inserted in one
transaction gets an identical `created_at` and anything ordered by it -- the
activity feed, a comment thread -- falls back to an arbitrary order.
`clock_timestamp()` reads the real clock on each insert. This matters as soon as
one action writes several rows: a receipt that becomes several expenses, or a
seed script.

Existing rows keep the timestamps they already have; only the default changes.

Revision ID: b0ff954ca818
Revises: 0a16607a0426
Create Date: 2026-09-10 22:13:23.056848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0ff954ca818'
down_revision: Union[str, Sequence[str], None] = '0a16607a0426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expense_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expense_comments_expense_id_created_at', 'expense_comments', ['expense_id', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('EXPENSE_ADDED', 'COMMENT_ADDED', 'SETTLEMENT_RECORDED', 'PAYMENT_REMINDER', name='notificationkind_check', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('expense_id', sa.Uuid(), nullable=True),
    sa.Column('settlement_id', sa.Uuid(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_id_read_at', 'notifications', ['user_id', 'read_at'], unique=False)
    # ### end Alembic commands ###

    # Autogenerate does not compare server defaults unless asked to, so these
    # three are written by hand.
    for table in ("expenses", "settlements", "groups"):
        op.alter_column(
            table,
            "created_at",
            server_default=sa.text("clock_timestamp()"),
            existing_type=sa.DateTime(timezone=True),
            existing_nullable=False,
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("expenses", "settlements", "groups"):
        op.alter_column(
            table,
            "created_at",
            server_default=sa.text("now()"),
            existing_type=sa.DateTime(timezone=True),
            existing_nullable=False,
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_id_read_at', table_name='notifications')
    op.drop_index('ix_notifications_user_id_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_expense_comments_expense_id_created_at', table_name='expense_comments')
    op.drop_table('expense_comments')
    # ### end Alembic commands ###
