/**
 * Stand-in for `virtual:pwa-register/react`.
 *
 * That module is generated by vite-plugin-pwa at build time and does not exist
 * under Vitest, so anything importing it fails to resolve -- and since the app
 * shell renders the update prompt, that is *every* screen test.
 *
 * The stub reports "no update waiting", which is the state every test wants: an
 * update banner appearing in the middle of an unrelated assertion would be noise.
 */
export function useRegisterSW() {
  return {
    needRefresh: [false, () => {}] as [boolean, (value: boolean) => void],
    offlineReady: [false, () => {}] as [boolean, (value: boolean) => void],
    updateServiceWorker: async () => {},
  }
}
